const user=[
    {
        id:1,
        name:"abhi",
        per:98.98
    },
    {
        id:2,
        name:"om",
        per:88.98
    },
    {
        id:3,
        name:"ram",
        per:77.98
    }
]
console.log(user[0].per);
console.log(user[1].per);
console.log(user[2].per);